### ISSUE TITLE
Data Request

### ISSUE THREAD

**Issue by CodeBrew2001** [LiYouru0228/STKG-JRCL#1]
Thanks for your wonderful work!
Would you mind releasing the dataset used in your work to help me verify the performance? Appreciate a lot!

**Comment by LiYouru0228** [comment]
Thanks for your interest. As stated in the ReadMe document, this project comes from a real commercial banking scenario in China, and this open source code is only an academic demo, not the commercially deployable one. Due to privacy protection and commercial secrets, we are sorry that the data used in the paper cannot be currently available for public. However, we have provided detailed interface description for the data used by this demo in the dataset directory. Based on this, you can easily make reference to the solution presented in our code for your own projects of concern.
